edition = "2023";

package profile_v3;

message ProfileStoreFile {
  StoreHeader header = 1;
  UserProfileStore store = 2;
}

message StoreHeader {
  uint32 version = 1;
  int64 created_at = 2;
  string name = 3;
}

message UserProfileStore {
  repeated Run runs = 1;
  repeated SourceDirectory sources = 2;
}

message SourceDirectory {
  uint32 id = 1;
  uint32 parent_id = 2;
  string path = 3;
}

message Run {
  ScenarioId scenario_id = 1;
  int64 start_time = 2;
  float scenario_length = 3;
  repeated ScenarioDataPoint data = 4;
  reserved 5;
  uint32 source_directory_id = 6;
  string source_filename = 7;
}

message ScenarioId {
  string name = 1;
  string hash = 2;
}

message ScenarioDataPoint {
  float time = 1;
  int32 shots = 2;
  int32 hits = 3;
  int32 misses = 4;
  float dmg = 5;
  float dmg_possible = 6;
  float score = 7;
  int32 kills = 8;
}
